name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Publicará el paquete cuando se cree un tag con el formato v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Verify npm registry
      run: npm config get registry
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'   

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
    
    - name: Check npm configuration
      run: |
        npm config list
        npm config get registry      

    - name: Publish to npm      
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public 
